// Reroute NJ — Shared line data
// NOT wrapped in IIFE — exposes LINE_DATA and LINE_ORDER as globals
// consumed by app.js, cards.js, widget.js, and widget.html.

var LINE_DATA = {
  "montclair-boonton": {
    name: "Montclair-Boonton Line",
    shortName: "Montclair-Boonton",
    color: "#7b2d8e",
    cssClass: "montclair-boonton",
    impactType: "hoboken-diversion",
    impactLevel: "severe",
    trainsBefore: 64,
    trainsAfter: 60,
    hub: "Newark Broad St",
    summary:
      "All weekday Midtown Direct trains diverted to Hoboken. Weekend service to Penn Station NY continues.",
    sources: [
      { label: "NJ Transit: Portal cutover service plan", url: "https://www.njtransit.com/portalcutover" },
      { label: "NJ Transit: Montclair-Boonton schedules", url: "https://www.njtransit.com/train-to?line=Montclair-Boonton%20Line" },
    ],
    branches: {
      montclair: "Montclair branch",
      boonton: "Boonton branch",
    },
    stations: [
      { id: "watsessing-ave", name: "Watsessing Avenue", branch: "montclair", zone: 3 },
      { id: "bloomfield", name: "Bloomfield", branch: "montclair", zone: 3 },
      { id: "glen-ridge", name: "Glen Ridge", branch: "montclair", zone: 3 },
      { id: "bay-street", name: "Bay Street (Montclair)", branch: "montclair", zone: 4 },
      { id: "walnut-street", name: "Walnut Street", branch: "montclair", zone: 4 },
      { id: "watchung-ave", name: "Watchung Avenue", branch: "montclair", zone: 4 },
      { id: "upper-montclair", name: "Upper Montclair", branch: "montclair", zone: 4 },
      { id: "mountain-ave", name: "Mountain Avenue", branch: "montclair", zone: 4 },
      { id: "montclair-heights", name: "Montclair Heights", branch: "montclair", zone: 4 },
      { id: "montclair-state", name: "Montclair State University", branch: "montclair", zone: 5 },
      { id: "little-falls", name: "Little Falls", branch: "boonton", zone: 5 },
      { id: "mountain-view", name: "Mountain View", branch: "boonton", zone: 5 },
      { id: "wayne-route23", name: "Wayne/Route 23", branch: "boonton", zone: 5 },
      { id: "lincoln-park", name: "Lincoln Park", branch: "boonton", zone: 6 },
      { id: "boonton", name: "Boonton", branch: "boonton", zone: 6 },
      { id: "mountain-lakes", name: "Mountain Lakes", branch: "boonton", zone: 7 },
      { id: "denville", name: "Denville", branch: "boonton", zone: 7 },
      { id: "dover-mb", name: "Dover", branch: "boonton", zone: 7 },
      { id: "lake-hopatcong", name: "Lake Hopatcong", branch: "boonton", zone: 8 },
      { id: "netcong", name: "Netcong", branch: "boonton", zone: 8 },
      { id: "mount-olive", name: "Mount Olive", branch: "boonton", zone: 9 },
      { id: "hackettstown-mb", name: "Hackettstown", branch: "boonton", zone: 10 },
    ],
  },

  "morris-essex": {
    name: "Morris & Essex Lines",
    shortName: "Morris & Essex",
    color: "#00a651",
    cssClass: "morris-essex",
    impactType: "hoboken-diversion",
    impactLevel: "severe",
    trainsBefore: 149,
    trainsAfter: 141,
    hub: "Newark Broad St",
    summary:
      "All weekday Midtown Direct trains on the Morristown Line and Gladstone Branch diverted to Hoboken. Weekend service to Penn Station NY continues.",
    sources: [
      { label: "NJ Transit: Portal cutover service plan", url: "https://www.njtransit.com/portalcutover" },
      { label: "NJ Transit: Morris & Essex schedules", url: "https://www.njtransit.com/train-to?line=Morris%20%26%20Essex%20Line" },
    ],
    branches: {
      morristown: "Morristown Line",
      gladstone: "Gladstone Branch",
    },
    stations: [
      // Morristown Line (east to west)
      { id: "orange", name: "Orange", branch: "morristown", zone: 2 },
      { id: "highland-ave", name: "Highland Avenue", branch: "morristown", zone: 3 },
      { id: "mountain-station", name: "Mountain Station", branch: "morristown", zone: 3 },
      { id: "south-orange", name: "South Orange", branch: "morristown", zone: 3 },
      { id: "maplewood", name: "Maplewood", branch: "morristown", zone: 3 },
      { id: "millburn", name: "Millburn", branch: "morristown", zone: 4 },
      { id: "short-hills", name: "Short Hills", branch: "morristown", zone: 4 },
      { id: "summit", name: "Summit", branch: "morristown", zone: 4 },
      { id: "chatham", name: "Chatham", branch: "morristown", zone: 5 },
      { id: "madison", name: "Madison", branch: "morristown", zone: 5 },
      { id: "convent-station", name: "Convent Station", branch: "morristown", zone: 5 },
      { id: "morristown", name: "Morristown", branch: "morristown", zone: 6 },
      { id: "morris-plains", name: "Morris Plains", branch: "morristown", zone: 6 },
      { id: "hanover", name: "Hanover", branch: "morristown", zone: 6 },
      { id: "whippany", name: "Whippany", branch: "morristown", zone: 6 },
      // Gladstone Branch (splits at Summit)
      { id: "murray-hill", name: "Murray Hill", branch: "gladstone", zone: 5 },
      { id: "new-providence", name: "New Providence", branch: "gladstone", zone: 5 },
      { id: "berkeley-heights", name: "Berkeley Heights", branch: "gladstone", zone: 5 },
      { id: "gillette", name: "Gillette", branch: "gladstone", zone: 5 },
      { id: "stirling", name: "Stirling", branch: "gladstone", zone: 6 },
      { id: "millington", name: "Millington", branch: "gladstone", zone: 6 },
      { id: "lyons", name: "Lyons", branch: "gladstone", zone: 6 },
      { id: "basking-ridge", name: "Basking Ridge", branch: "gladstone", zone: 6 },
      { id: "bernardsville", name: "Bernardsville", branch: "gladstone", zone: 7 },
      { id: "far-hills", name: "Far Hills", branch: "gladstone", zone: 7 },
      { id: "peapack", name: "Peapack", branch: "gladstone", zone: 7 },
      { id: "gladstone", name: "Gladstone", branch: "gladstone", zone: 7 },
    ],
  },

  "northeast-corridor": {
    name: "Northeast Corridor",
    shortName: "Northeast Corridor",
    color: "#ee3a43",
    cssClass: "northeast-corridor",
    impactType: "reduced-service",
    impactLevel: "moderate",
    trainsBefore: 133,
    trainsAfter: 112,
    hub: "Newark Penn",
    summary:
      "Trains still run to Penn Station NY, but service is reduced from 133 to 112 daily trains due to single-track operation between Newark and Secaucus.",
    sources: [
      { label: "NJ Transit: Portal cutover service plan", url: "https://www.njtransit.com/portalcutover" },
      { label: "NJ Transit: Northeast Corridor schedules", url: "https://www.njtransit.com/train-to?line=Northeast%20Corridor%20Line" },
    ],
    branches: {
      nec: "Northeast Corridor",
    },
    stations: [
      { id: "trenton", name: "Trenton", branch: "nec", zone: 9 },
      { id: "hamilton", name: "Hamilton", branch: "nec", zone: 8 },
      { id: "princeton-jct", name: "Princeton Junction", branch: "nec", zone: 7 },
      { id: "jersey-ave", name: "Jersey Avenue", branch: "nec", zone: 7 },
      { id: "new-brunswick", name: "New Brunswick", branch: "nec", zone: 6 },
      { id: "edison", name: "Edison", branch: "nec", zone: 5 },
      { id: "metuchen", name: "Metuchen", branch: "nec", zone: 5 },
      { id: "metropark", name: "Metropark", branch: "nec", zone: 4 },
      { id: "rahway", name: "Rahway", branch: "nec", zone: 4 },
      { id: "linden", name: "Linden", branch: "nec", zone: 3 },
      { id: "elizabeth", name: "Elizabeth", branch: "nec", zone: 3 },
      { id: "north-elizabeth", name: "North Elizabeth", branch: "nec", zone: 3 },
      { id: "newark-airport", name: "Newark Airport", branch: "nec", zone: 2 },
      { id: "newark-penn", name: "Newark Penn Station", branch: "nec", zone: 1 },
      { id: "secaucus", name: "Secaucus Junction", branch: "nec", zone: 1 },
    ],
  },

  "north-jersey-coast": {
    name: "North Jersey Coast Line",
    shortName: "North Jersey Coast",
    color: "#0082c8",
    cssClass: "north-jersey-coast",
    impactType: "reduced-service",
    impactLevel: "moderate",
    trainsBefore: 109,
    trainsAfter: 92,
    hub: "Secaucus Junction",
    summary:
      "Trains still run to Penn Station NY, but reduced from 109 to 92 daily trains. Significant schedule changes. Perth Amboy/Woodbridge riders get bus cross-honoring to Port Authority.",
    sources: [
      { label: "NJ Transit: Portal cutover service plan", url: "https://www.njtransit.com/portalcutover" },
      { label: "NJ Transit: North Jersey Coast schedules", url: "https://www.njtransit.com/train-to?line=North%20Jersey%20Coast%20Line" },
    ],
    branches: {
      njcl: "North Jersey Coast Line",
    },
    stations: [
      { id: "bay-head", name: "Bay Head", branch: "njcl", zone: 10 },
      { id: "point-pleasant", name: "Point Pleasant Beach", branch: "njcl", zone: 9 },
      { id: "manasquan", name: "Manasquan", branch: "njcl", zone: 9 },
      { id: "spring-lake", name: "Spring Lake", branch: "njcl", zone: 8 },
      { id: "belmar", name: "Belmar", branch: "njcl", zone: 8 },
      { id: "bradley-beach", name: "Bradley Beach", branch: "njcl", zone: 8 },
      { id: "asbury-park", name: "Asbury Park", branch: "njcl", zone: 7 },
      { id: "allenhurst", name: "Allenhurst", branch: "njcl", zone: 7 },
      { id: "elberon", name: "Elberon", branch: "njcl", zone: 7 },
      { id: "long-branch", name: "Long Branch", branch: "njcl", zone: 6 },
      { id: "little-silver", name: "Little Silver", branch: "njcl", zone: 6 },
      { id: "red-bank", name: "Red Bank", branch: "njcl", zone: 6 },
      { id: "middletown", name: "Middletown", branch: "njcl", zone: 5 },
      { id: "hazlet", name: "Hazlet", branch: "njcl", zone: 5 },
      { id: "aberdeen-matawan", name: "Aberdeen-Matawan", branch: "njcl", zone: 5 },
      { id: "south-amboy", name: "South Amboy", branch: "njcl", zone: 5 },
      { id: "perth-amboy", name: "Perth Amboy", branch: "njcl", zone: 5 },
      { id: "woodbridge", name: "Woodbridge", branch: "njcl", zone: 4 },
    ],
  },

  "raritan-valley": {
    name: "Raritan Valley Line",
    shortName: "Raritan Valley",
    color: "#faa634",
    cssClass: "raritan-valley",
    impactType: "newark-termination",
    impactLevel: "severe",
    trainsBefore: "All trains",
    trainsAfter: "No one-seat rides to PSNY",
    hub: "Newark Penn",
    summary:
      "All one-seat rides to Penn Station New York are suspended. All trains now originate and terminate at Newark Penn Station. Transfer to NEC at Newark Penn to reach PSNY.",
    sources: [
      { label: "NJ Transit: Portal cutover service plan", url: "https://www.njtransit.com/portalcutover" },
      { label: "NJ Transit: Raritan Valley schedules", url: "https://www.njtransit.com/train-to?line=Raritan%20Valley%20Line" },
    ],
    branches: {
      rvl: "Raritan Valley Line",
    },
    stations: [
      { id: "high-bridge", name: "High Bridge", branch: "rvl", zone: 9 },
      { id: "annandale", name: "Annandale", branch: "rvl", zone: 8 },
      { id: "lebanon", name: "Lebanon", branch: "rvl", zone: 8 },
      { id: "white-house", name: "White House", branch: "rvl", zone: 7 },
      { id: "north-branch", name: "North Branch", branch: "rvl", zone: 7 },
      { id: "raritan", name: "Raritan", branch: "rvl", zone: 6 },
      { id: "somerville", name: "Somerville", branch: "rvl", zone: 6 },
      { id: "bridgewater", name: "Bridgewater", branch: "rvl", zone: 6 },
      { id: "bound-brook", name: "Bound Brook", branch: "rvl", zone: 6 },
      { id: "dunellen", name: "Dunellen", branch: "rvl", zone: 5 },
      { id: "plainfield", name: "Plainfield", branch: "rvl", zone: 5 },
      { id: "fanwood", name: "Fanwood", branch: "rvl", zone: 4 },
      { id: "westfield", name: "Westfield", branch: "rvl", zone: 4 },
      { id: "cranford", name: "Cranford", branch: "rvl", zone: 3 },
      { id: "roselle-park", name: "Roselle Park", branch: "rvl", zone: 3 },
      { id: "union", name: "Union", branch: "rvl", zone: 3 },
    ],
  },
};

// Order to display lines
var LINE_ORDER = [
  "montclair-boonton",
  "morris-essex",
  "northeast-corridor",
  "north-jersey-coast",
  "raritan-valley",
];
