name: Feature request
description: Suggest a new tool or enhancement
labels: ["enhancement"]
body:
  - type: textarea
    id: problem
    attributes:
      label: What problem does this solve?
      description: Describe the rider experience you're trying to improve.
      placeholder: "Riders transferring at Hoboken don't know which PATH train to take for their Manhattan destination."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: What would you like to see?
      description: Describe the feature or enhancement.
      placeholder: "A PATH connection guide that shows which train to take based on your final destination."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Are there other ways to solve this?
    validations:
      required: false
